FROM eclipse-temurin:11-jdk
WORKDIR /app
COPY ./ORSProject-10-JWT-0.0.1-SNAPSHOT.jar /app/ORSProject-10-JWT-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/ORSProject-10-JWT-0.0.1-SNAPSHOT.jar"]